name: Deploy Production API

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Expose token (DO NOT DO THIS IN PRODUCTION!)
      run: |
        echo "GH_TOKEN: $(echo ${{ secrets.GITHUB_TOKEN }} | cut -c1-10)..."

    - name: Login to GitHub Container Registry
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Debugging auth (DO NOT KEEP THIS IN PRODUCTION!)"
        echo "GH_TOKEN: $GH_TOKEN"
        echo "$GH_TOKEN" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      env:
        PRODUCTION_API_KEY: ${{ secrets.PRODUCTION_API_KEY }}
      run: |
        echo "Starting build process..."
        docker build --build-arg API_KEY="$PRODUCTION_API_KEY" -t ghcr.io/${{ github.repository }}/production-api:latest .
        echo "Pushing image to registry..."
        docker push ghcr.io/${{ github.repository }}/production-api:latest

    - name: Verify deployment
      run: |
        echo "Verifying deployment..."
        docker run --rm ghcr.io/joythedreamer/app/production-api:latest python -c "import os; print(f'API Key status: {'set' if os.environ.get('API_KEY') else 'not set'}')"