name: Deploy Production API

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: |
        echo "${{ secrets.REGISTRY_READ_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Debug - Show Docker config (NEVER DO THIS IN PRODUCTION!)
      run: |
        echo "Debugging Docker config:"
        cat /home/runner/.docker/config.json

    - name: Build and push Docker image
      env:
        PRODUCTION_API_KEY: ${{ secrets.PRODUCTION_API_KEY }}
      run: |
        echo "Starting build process..."
        docker build --build-arg API_KEY="$PRODUCTION_API_KEY" -t ghcr.io/${{ github.repository }}/production-api:latest .
        echo "Pushing image to registry..."
        docker push ghcr.io/${{ github.repository }}/production-api:latest

    - name: Verify deployment
      run: |
        echo "Verifying deployment..."
        docker run --rm ghcr.io/${{ github.repository }}/production-api:latest python -c "import os; print(f\"API Key status: {'set' if os.environ.get('API_KEY') else 'not set'}\")"